cf:
  api: https://api.cf.example.com
  client_id: autoscaler_client_id
  secret: autoscaler_client_secret
  skip_ssl_validation: true
server:
  port: 8080
cf_server:
  port: 8082
health:
  server_config:
    port: 8081
logging:
  level: info
readiness_timeout: 30s
nats:
  urls:
    - nats-mtls://nats.service.cf.internal:4224
  refresh_seconds: 20
  stale_seconds: 120
  tls:
    key_file: "../testcerts/nats-client.key"
    cert_file: "../testcerts/nats-client.crt"
    ca_file: "../testcerts/nats-ca.crt"
scaling_engine:
  scaling_engine_url: https://scalingengine.cf.example.com
  tls:
    key_file: "../testcerts/client.key"
    cert_file: "../testcerts/client.crt"
    ca_file: "../testcerts/ca.crt"
routing_api:
  url: https://api.cf.example.com
  skip_ssl_validation: true
  uaa:
    url: https://uaa.cf.example.com
    client_id: routing_api_client
    client_secret: routing_api_secret
    grant_type: client_credentials
