/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Mon Feb 29 13:37:57 CST 2016
 */

package org.cloudfoundry.autoscaler.servicebroker.nls;

public class messages_pl extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "AlreadyBindedAnotherService", "[G'\uff23\uff37\uff33\uff23\uff362004\uff25: \uff21\uff4e\uff4f\uff54\uff48\uff45r Auto-Scaling service is already bound to application.\u0e0f\u0e39\u0130\u0131\uff5c]" },
      { "BindServiceFail", "[G''\uff23\uff37\uff33\uff23\uff362003\uff25: \uff34\uff48\uff45 \uff21\uff55\uff54\uff4f-\uff33\uff43aling service broker failed to bind the service instance [{0}].\u0e0f\u0e39\u0130\u0131\uff5c]" },
      { "ConfigurationLoadFail", "[G'\uff23\uff37\uff33\uff23\uff362001\uff25: \uff34\uff48\uff45 \uff21\uff55\uff54o-Scaling service broker is not configured correctly.\u0e0f\u0e39\u0130\u0131\uff5c]" },
      { "DeleteServiceFail", "[G''\uff23\uff37\uff33\uff23\uff362005\uff25: \uff34\uff48\uff45 \uff21\uff55\uff54\uff4f-\uff33\uff43\uff41ling service broker failed to delete the service instance [{0}].\u0e0f\u0e39\u0130\u0131\uff5c]" },
      { "ServerUrlMappingNotFound", "[G'\uff23\uff37\uff33\uff23\uff362006\uff25: \uff34\uff48\uff49\uff53 \uff21\uff55\uff54\uff4f-\uff33\uff43\uff41\uff4c\uff49\uff4e\uff47 \uff53\uff45\uff52\uff56\uff49ce is broken. Please delete the service and rebind the application to a new service.\u0e0f\u0e39\u0130\u0131\uff5c]" },
      { "UnbindServiceFail", "[G''\uff23\uff37\uff33\uff23\uff362002\uff25: \uff34\uff48\uff45 \uff21\uff55\uff54\uff4f-\uff33\uff43\uff41ling service broker failed to unbind the service instance [{0}].\u0e0f\u0e39\u0130\u0131\uff5c]" }
   };
}
