/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Mon Feb 29 13:37:57 CST 2016
 */

package org.cloudfoundry.autoscaler.servicebroker.nls;

public class messages_it extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "AlreadyBindedAnotherService", "CWSCV2004E: Un altro servizio Auto-Scaling \u00e8 gi\u00e0 associato all'applicazione." },
      { "BindServiceFail", "CWSCV2003E: Il broker del servizio Auto-Scaling non \u00e8 riuscito a eseguire il bind all''istanza del servizio {0}." },
      { "ConfigurationLoadFail", "CWSCV2001E: Il broker del servizio Auto-Scaling non \u00e8 configurato correttamente." },
      { "DeleteServiceFail", "CWSCV2005E: Il broker del servizio Auto-Scaling non \u00e8 riuscito a eliminare l''istanza del servizio {0}." },
      { "ServerUrlMappingNotFound", "CWSCV2006E: Questo servizio Auto-Scaling non funziona. Eliminare il servizio e rieseguire il bind dell'applicazione a un nuovo servizio." },
      { "UnbindServiceFail", "CWSCV2002E: Il broker del servizio Auto-Scaling non \u00e8 riuscito ad annullare il bind all''istanza del servizio {0}." }
   };
}
