/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Mon Feb 29 13:37:57 CST 2016
 */

package org.cloudfoundry.autoscaler.servicebroker.nls;

public class messages_pt extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "AlreadyBindedAnotherService", "CWSCV2004E: Outro servi\u00e7o Auto-Scaling j\u00e1 est\u00e1 ligado ao aplicativo." },
      { "BindServiceFail", "CWSCV2003E: O broker do servi\u00e7o Auto-Scaling falhou ao ligar a inst\u00e2ncia de servi\u00e7o {0}." },
      { "ConfigurationLoadFail", "CWSCV2001E: O broker do servi\u00e7o Auto-Scaling n\u00e3o est\u00e1 configurado corretamente." },
      { "DeleteServiceFail", "CWSCV2005E: O broker do servi\u00e7o Auto-Scaling falhou ao excluir a inst\u00e2ncia de servi\u00e7o {0}." },
      { "ServerUrlMappingNotFound", "CWSCV2006E: Este servi\u00e7o de Auto-Scaling foi interrompido. Exclua o servi\u00e7o e religue o aplicativo a um novo servi\u00e7o." },
      { "UnbindServiceFail", "CWSCV2002E: O broker do servi\u00e7o Auto-Scaling falhou ao desvincular a inst\u00e2ncia de servi\u00e7o {0}." }
   };
}
