/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Mon Feb 29 13:37:57 CST 2016
 */

package org.cloudfoundry.autoscaler.servicebroker.nls;

public class messages extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "AlreadyBindedAnotherService", "CWSCV2004E: Another Auto-Scaling service is already bound to application." },
      { "BindServiceFail", "CWSCV2003E: The Auto-Scaling service broker failed to bind the service instance {0}." },
      { "DeleteServiceFail", "CWSCV2005E: The Auto-Scaling service broker failed to delete the service instance {0}." },
      { "EnableServiceFail", "CWSCV2005E: The Auto-Scaling service broker failed to enable/disable the service instance {0}." },
      { "ParseJSONError", "CWSCV2001E: The Auto-Scaling service cannot parse the input JSON strings." },
      { "QueryServiceEnabledInfoFail", "CWSCV2005E: The Auto-Scaling service broker failed to load enablement information of the service instance {0}." },
      { "ServerUrlMappingNotFound", "CWSCV2006E: This Auto-Scaling service is broken. Please delete the service and rebind the application to a new service." },
      { "UnbindServiceFail", "CWSCV2002E: The Auto-Scaling service broker failed to unbind the service instance {0}." }
   };
}
