/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Mon Feb 29 13:37:57 CST 2016
 */

package org.cloudfoundry.autoscaler.servicebroker.nls;

public class messages_de extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "AlreadyBindedAnotherService", "CWSCV2004E: Ein anderer Service 'Auto-Scaling' ist bereits an die Anwendung gebunden." },
      { "BindServiceFail", "CWSCV2003E: Der Service-Broker f\u00fcr Auto-Scaling konnte f\u00fcr Serviceinstanz {0} keine Bindung erstellen." },
      { "ConfigurationLoadFail", "CWSCV2001E: Der Service-Broker f\u00fcr Auto-Scaling ist nicht ordnungsgem\u00e4\u00df konfiguriert." },
      { "DeleteServiceFail", "CWSCV2005E: Der Service-Broker f\u00fcr Auto-Scaling konnte Serviceinstanz {0} nicht l\u00f6schen." },
      { "ServerUrlMappingNotFound", "CWSCV2006E: Dieser Service 'Auto-Scaling' ist unterbrochen. L\u00f6schen Sie den Service und binden Sie die Anwendung erneut an einen neuen Service." },
      { "UnbindServiceFail", "CWSCV2002E: Der Service-Broker f\u00fcr Auto-Scaling konnte die Bindung f\u00fcr Serviceinstanz {0} nicht aufheben." }
   };
}
