broker_server:
  port: 8080
public_api_server:
  port: 8081
logging:
  level: debug
broker_username: brokeruser
broker_password: supersecretpassword
db:
  binding_db:
    url: postgres://postgres:postgres@localhost/autoscaler?sslmode=disable
    max_open_connections: 10
    max_idle_connections: 5
    connection_max_lifetime: 60s
  policy_db:
    url: postgres://postgres:postgres@localhost/autoscaler?sslmode=disable
    max_open_connections: 10
    max_idle_connections: 5
    connection_max_lifetime: 60s
dashboard_redirect_uri: "https://dashboard-redirect-uri-settings.example.com"
catalog_schema_path: "/var/vcap/jobs/api/packages/api/config/catalog.schema.json"
catalog_path: "/var/vcap/jobs/api/packages/api/config/catalog.json"
policy_schema_path: "/var/vcap/jobs/api/packages/api/config/policy.schema.json"
scaling_engine:
  scaling_engine_url: http://localhost:8083
  tls:
    key_file: /var/vcap/jobs/autoscaler/config/certs/se.key
    cert_file: /var/vcap/jobs/autoscaler/config/certs/se.crt
    ca_file: /var/vcap/jobs/autoscaler/config/certs/autoscaler-ca.crt
event_generator:
  event_generator_url: http://localhost:8083
  tls:
    key_file: /var/vcap/jobs/autoscaler/config/certs/eg.key
    cert_file: /var/vcap/jobs/autoscaler/config/certs/eg.crt
    ca_file: /var/vcap/jobs/autoscaler/config/certs/autoscaler-ca.crt
scheduler:
  scheduler_url: http://localhost:8082
  tls:
    key_file: /var/vcap/jobs/autoscaler/config/certs/eg.key
    cert_file: /var/vcap/jobs/autoscaler/config/certs/eg.crt
    ca_file: /var/vcap/jobs/autoscaler/config/certs/autoscaler-ca.crt
metrics_forwarder:
  metrics_forwarder_url: http://localhost:8088
  metrics_forwarder_mtls_url: http://localhost:8088
cf:
  api: https://api.example.com
  client_id: client-id
  secret: client-secret
  skip_ssl_validation: false
  grant_type: client_credentials
info_file_path: /var/vcap/jobs/golangapiserver/config/info.json
rate_limit:
  max_amount: 10
  valid_duration: 1s
