name: 'Acceptance Tests Common'
description: 'Common steps for all acceptance tests'
inputs:
  ssh-key:  # id of input
    description: 'The BBL ssh key'
    required: true
runs:
  using: "composite"
  steps:
    - name: clone BBL repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        repository: cloudfoundry/app-autoscaler-env-bbl-state
        ref: main
        ssh-key: ${{ inputs.ssh-key }}
        path: bbl
