name: 'Acceptance Tests Common'
description: 'Common steps for all acceptance tests'
inputs:
  ssh-key:  # id of input
    description: 'The BBL ssh key'
    required: true
runs:
  using: "composite"
  steps:
    - name: clone BBL repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        repository: cloudfoundry/app-autoscaler-env-bbl-state
        ref: main
        ssh-key: ${{ inputs.ssh-key }}
        path: bbl
