/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:19 CST 2016
 */

package org.cloudfoundry.autoscaler.nls;

public class ServerMessages_es extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV3006E: No se ha encontrado la aplicaci\u00f3n: {0}" },
      { "RestResponseErrorMsg_applist_not_empty_error", "CWSCV3005E: La lista de aplicaciones no est\u00e1 vac\u00eda para la configuraci\u00f3n: {0}" },
      { "RestResponseErrorMsg_build_JSON_error", "CWSCV3001E: El servidor de Auto-Scaling no puede crear las series JSON." },
      { "RestResponseErrorMsg_cloud_error", "CWSCV3007E: Error al llamar a las API de CloudFoundry: {0}" },
      { "RestResponseErrorMsg_config_exist_error", "CWSCV3003E: No se puede llevar a cabo la configuraci\u00f3n: {0}" },
      { "RestResponseErrorMsg_database_error", "CWSCV3009E: Se ha producido un error de la base de datos: {0}" },
      { "RestResponseErrorMsg_metric_not_supported_error", "CWSCV3008E: No se da soporte al tipo de m\u00e9trica: {0}" },
      { "RestResponseErrorMsg_no_attached_policy_error", "CWSCV3010E: No hay ninguna pol\u00edtica adjunta a la aplicaci\u00f3n." },
      { "RestResponseErrorMsg_parse_JSON_error", "CWSCV3002E: El servidor de Auto-Scaling no puede analizar las series JSON." },
      { "RestResponseErrorMsg_policy_not_found_error", "CWSCV3004E: No se ha encontrado la pol\u00edtica: {0}" }
   };
}
