/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:19 CST 2016
 */

package org.cloudfoundry.autoscaler.nls;

public class ServerMessages_it extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV3006E: Applicazione non trovata: {0}" },
      { "RestResponseErrorMsg_applist_not_empty_error", "CWSCV3005E: L''elenco di applicazioni non \u00e8 vuoto per la configurazione: {0}" },
      { "RestResponseErrorMsg_build_JSON_error", "CWSCV3001E: Il server Auto-Scaling non riesce a creare le stringe JSON." },
      { "RestResponseErrorMsg_cloud_error", "CWSCV3007E: Chiamata alle API CloudFoundry non riuscita: {0}" },
      { "RestResponseErrorMsg_config_exist_error", "CWSCV3003E: Impossibile eseguire la configurazione: {0}" },
      { "RestResponseErrorMsg_database_error", "CWSCV3009E: Errore database: {0}" },
      { "RestResponseErrorMsg_metric_not_supported_error", "CWSCV3008E: Tipo di metrica non supportato: {0}" },
      { "RestResponseErrorMsg_no_attached_policy_error", "CWSCV3010E: Nessuna politica allegata all'applicazione." },
      { "RestResponseErrorMsg_parse_JSON_error", "CWSCV3002E: Il server Auto-Scaling non riesce ad analizzare le stringe JSON." },
      { "RestResponseErrorMsg_policy_not_found_error", "CWSCV3004E: Politica non trovata: {0}" }
   };
}
