/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:19 CST 2016
 */

package org.cloudfoundry.autoscaler.nls;

public class ServerMessages_zh extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV3006E: \u672a\u627e\u5230\u5e94\u7528\u7a0b\u5e8f\uff1a{0}" },
      { "RestResponseErrorMsg_applist_not_empty_error", "CWSCV3005E: \u9488\u5bf9\u914d\u7f6e\u7684\u5e94\u7528\u7a0b\u5e8f\u5217\u8868\u4e0d\u80fd\u4e3a\u7a7a\uff1a{0}" },
      { "RestResponseErrorMsg_build_JSON_error", "CWSCV3001E: Auto-Scaling \u670d\u52a1\u5668\u65e0\u6cd5\u6784\u5efa JSON \u5b57\u7b26\u4e32\u3002" },
      { "RestResponseErrorMsg_cloud_error", "CWSCV3007E: \u8c03\u7528 CloudFoundry API \u5931\u8d25\uff1a{0}" },
      { "RestResponseErrorMsg_config_exist_error", "CWSCV3003E: \u65e0\u6cd5\u5b8c\u6210\u914d\u7f6e\uff1a{0}" },
      { "RestResponseErrorMsg_database_error", "CWSCV3009E: \u53d1\u751f\u6570\u636e\u5e93\u9519\u8bef\uff1a{0}" },
      { "RestResponseErrorMsg_metric_not_supported_error", "CWSCV3008E: \u4e0d\u652f\u6301\u5ea6\u91cf\u503c\u7c7b\u578b\uff1a{0}" },
      { "RestResponseErrorMsg_no_attached_policy_error", "CWSCV3010E: \u672a\u5c06\u4efb\u4f55\u7b56\u7565\u8fde\u63a5\u81f3\u5e94\u7528\u7a0b\u5e8f\u3002" },
      { "RestResponseErrorMsg_parse_JSON_error", "CWSCV3002E: Auto-Scaling \u670d\u52a1\u5668\u65e0\u6cd5\u89e3\u6790 JSON \u5b57\u7b26\u4e32\u3002" },
      { "RestResponseErrorMsg_policy_not_found_error", "CWSCV3004E: \u672a\u627e\u5230\u7b56\u7565\uff1a{0}" }
   };
}
