/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:19 CST 2016
 */

package org.cloudfoundry.autoscaler.nls;

public class ServerMessages_ko extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV3006E: \uc560\ud50c\ub9ac\ucf00\uc774\uc158\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc74c: {0}" },
      { "RestResponseErrorMsg_applist_not_empty_error", "CWSCV3005E: \uc560\ud50c\ub9ac\ucf00\uc774\uc158 \ubaa9\ub85d\uc774 \uad6c\uc131\uc5d0 \ub300\ud574 \ube44\uc5b4 \uc788\uc9c0 \uc54a\uc74c: {0}" },
      { "RestResponseErrorMsg_build_JSON_error", "CWSCV3001E: Auto-Scaling \uc11c\ubc84\uac00 JSON \ubb38\uc790\uc5f4\uc744 \ube4c\ub4dc\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4." },
      { "RestResponseErrorMsg_cloud_error", "CWSCV3007E: CloudFoundry API \ud638\ucd9c \uc2e4\ud328: {0}" },
      { "RestResponseErrorMsg_config_exist_error", "CWSCV3003E: \uad6c\uc131\uc744 \uc644\ub8cc\ud560 \uc218 \uc5c6\uc74c: {0}" },
      { "RestResponseErrorMsg_database_error", "CWSCV3009E: \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc624\ub958 \ubc1c\uc0dd: {0}" },
      { "RestResponseErrorMsg_metric_not_supported_error", "CWSCV3008E: \uba54\ud2b8\ub9ad \uc720\ud615\uc774 \uc9c0\uc6d0\ub418\uc9c0 \uc54a\uc74c: {0}" },
      { "RestResponseErrorMsg_no_attached_policy_error", "CWSCV3010E: \uc560\ud50c\ub9ac\ucf00\uc774\uc158\uc5d0 \uc5f0\uacb0\ub41c \uc815\ucc45\uc774 \uc5c6\uc2b5\ub2c8\ub2e4." },
      { "RestResponseErrorMsg_parse_JSON_error", "CWSCV3002E: Auto-Scaling \uc11c\ubc84\uac00 JSON \ubb38\uc790\uc5f4\uc744 \uad6c\ubb38 \ubd84\uc11d\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4." },
      { "RestResponseErrorMsg_policy_not_found_error", "CWSCV3004E: \uc815\ucc45\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc74c: {0}" }
   };
}
