/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:19 CST 2016
 */

package org.cloudfoundry.autoscaler.nls;

public class ServerMessages_zh_TW extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV3006E: \u627e\u4e0d\u5230\u61c9\u7528\u7a0b\u5f0f\uff1a{0}" },
      { "RestResponseErrorMsg_applist_not_empty_error", "CWSCV3005E: \u914d\u7f6e\u7684\u61c9\u7528\u7a0b\u5f0f\u6e05\u55ae\u4e0d\u662f\u7a7a\u7684\uff1a{0}" },
      { "RestResponseErrorMsg_build_JSON_error", "CWSCV3001E: \u300cAuto-Scaling\u300d\u4f3a\u670d\u5668\u7121\u6cd5\u5efa\u7f6e JSON \u5b57\u4e32\u3002" },
      { "RestResponseErrorMsg_cloud_error", "CWSCV3007E: \u547c\u53eb CloudFoundry API \u5931\u6557\uff1a{0}" },
      { "RestResponseErrorMsg_config_exist_error", "CWSCV3003E: \u7121\u6cd5\u5b8c\u6210\u914d\u7f6e\uff1a{0}" },
      { "RestResponseErrorMsg_database_error", "CWSCV3009E: \u767c\u751f\u8cc7\u6599\u5eab\u932f\u8aa4\uff1a{0}" },
      { "RestResponseErrorMsg_metric_not_supported_error", "CWSCV3008E: \u4e0d\u652f\u63f4\u5ea6\u91cf\u985e\u578b\uff1a{0}" },
      { "RestResponseErrorMsg_no_attached_policy_error", "CWSCV3010E: \u6c92\u6709\u539f\u5247\u9644\u52a0\u81f3\u61c9\u7528\u7a0b\u5f0f\u3002" },
      { "RestResponseErrorMsg_parse_JSON_error", "CWSCV3002E: \u300cAuto-Scaling\u300d\u4f3a\u670d\u5668\u7121\u6cd5\u5256\u6790 JSON \u5b57\u4e32\u3002" },
      { "RestResponseErrorMsg_policy_not_found_error", "CWSCV3004E: \u627e\u4e0d\u5230\u539f\u5247\uff1a{0}" }
   };
}
