/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:19 CST 2016
 */

package org.cloudfoundry.autoscaler.nls;

public class ServerMessages extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV3006E: The application is not found: {0}" },
      { "RestResponseErrorMsg_applist_not_empty_error", "CWSCV3005E: The application list is not empty for configuration: {0}" },
      { "RestResponseErrorMsg_build_JSON_error", "CWSCV3001E: The Auto-Scaling server cannot build the JSON strings." },
      { "RestResponseErrorMsg_cloud_error", "CWSCV3007E: Calling CloudFoundry APIs failed: {0}" },
      { "RestResponseErrorMsg_config_exist_error", "CWSCV3003E: Configuration cannot be done: {0}" },
      { "RestResponseErrorMsg_database_error", "CWSCV3009E: Database error occurs: {0}" },
      { "RestResponseErrorMsg_metric_not_supported_error", "CWSCV3008E: The metric type is not supported: {0}" },
      { "RestResponseErrorMsg_no_attached_policy_error", "CWSCV3010E: No policy is attached to the application." },
      { "RestResponseErrorMsg_parse_JSON_error", "CWSCV3002E: The Auto-Scaling server cannot parse the JSON strings." },
      { "RestResponseErrorMsg_policy_not_found_error", "CWSCV3004E: The policy is not found: {0}" }
   };
}
