/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:19 CST 2016
 */

package org.cloudfoundry.autoscaler.nls;

public class ServerMessages_ja extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV3006E: \u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093: {0}" },
      { "RestResponseErrorMsg_applist_not_empty_error", "CWSCV3005E: \u69cb\u6210\u306e\u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u30fb\u30ea\u30b9\u30c8\u304c\u7a7a\u3067\u306f\u3042\u308a\u307e\u305b\u3093: {0}" },
      { "RestResponseErrorMsg_build_JSON_error", "CWSCV3001E: Auto-Scaling \u30b5\u30fc\u30d0\u30fc\u3067 JSON \u30b9\u30c8\u30ea\u30f3\u30b0\u3092\u4f5c\u6210\u3067\u304d\u307e\u305b\u3093\u3002" },
      { "RestResponseErrorMsg_cloud_error", "CWSCV3007E: CloudFoundry API \u306e\u547c\u3073\u51fa\u3057\u306b\u5931\u6557\u3057\u307e\u3057\u305f: {0}" },
      { "RestResponseErrorMsg_config_exist_error", "CWSCV3003E: \u69cb\u6210\u3092\u5b9f\u884c\u3067\u304d\u307e\u305b\u3093: {0}" },
      { "RestResponseErrorMsg_database_error", "CWSCV3009E: \u30c7\u30fc\u30bf\u30d9\u30fc\u30b9\u30fb\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u307e\u3057\u305f: {0}" },
      { "RestResponseErrorMsg_metric_not_supported_error", "CWSCV3008E: \u30e1\u30c8\u30ea\u30af\u30b9\u30fb\u30bf\u30a4\u30d7\u304c\u30b5\u30dd\u30fc\u30c8\u3055\u308c\u3066\u3044\u307e\u305b\u3093: {0}" },
      { "RestResponseErrorMsg_no_attached_policy_error", "CWSCV3010E: \u30dd\u30ea\u30b7\u30fc\u304c\u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u306b\u4ed8\u52a0\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002" },
      { "RestResponseErrorMsg_parse_JSON_error", "CWSCV3002E: Auto-Scaling \u30b5\u30fc\u30d0\u30fc\u3067 JSON \u30b9\u30c8\u30ea\u30f3\u30b0\u3092\u89e3\u6790\u3067\u304d\u307e\u305b\u3093\u3002" },
      { "RestResponseErrorMsg_policy_not_found_error", "CWSCV3004E: \u30dd\u30ea\u30b7\u30fc\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093: {0}" }
   };
}
