package ui

const (
	OK                 = "OK"
	FAILED             = "FAILED"
	NoEndpoint         = "No api endpoint set. Use 'cf autoscaling-api' to set an endpoint."
	APIEndpoint        = "Autoscaler api endpoint: %s"
	SetAPIEndpoint     = "Setting AutoScaler api endpoint to %s..."
	UnsetAPIEndpoint   = "Unsetting AutoScaler api endpoint."
	InvalidAPIEndpoint = "Invalid AutoScaler API endpoint : %s"
	InvalidSSLCerts    = "Invalid SSL Cert for %s \nTIP: Use --skip-ssl-validation to continue with an insecure API endpoint."
	Unauthorized       = "Unauthorized. Failed to access AutoScaler API Endpoint %s with the access token generated by %s."
	LoginRequired      = "You must be logged in %s first"
	PolicyNotFound     = "No policy defined for app %s."
)
