package ui

const (
	OK     = "OK"
	FAILED = "FAILED"

	NoEndpoint         = "No api endpoint set. Use 'cf autoscaling-api' to set an endpoint."
	APIEndpoint        = "Autoscaler api endpoint: %s."
	SetAPIEndpoint     = "Setting AutoScaler api endpoint to %s..."
	UnsetAPIEndpoint   = "Unsetting AutoScaler api endpoint."
	InvalidAPIEndpoint = "Invalid AutoScaler API endpoint : %s."
	InvalidSSLCerts    = "Invalid SSL Cert for %s \nTIP: Use --skip-ssl-validation to continue with an insecure API endpoint."

	Unauthorized  = "Unauthorized. Failed to access AutoScaler API Endpoint %s with the access token generated by %s."
	LoginRequired = "You must be logged in %s first."

	FailToLoadPolicyFile = "Failed to read policy file %s."
	PolicyNotFound       = "No policy defined for app %s."
	InvalidPolicy        = "Invalid policy definition: %v."

	ShowPolicyHint   = "Showing policy for app %s..."
	AttachPolicyHint = "Attaching policy for app %s..."
	DetachPolicyHint = "Detaching policy for app %s..."
)
