name: Make devbox shellenv available
description: Exports required devbox env vars to GITHUB_ENV

runs:
  using: composite
  steps:
    - name: Export devbox env vars
      shell: bash
      run: |
        eval "$(devbox shellenv)"
        while IFS= read -r -d '' var; do
          key="${var%%=*}"
          value="${var#*=}"
          [[ "$value" != *$'\n'* ]] && echo "$key=$value" >> "$GITHUB_ENV"
        done < <(env -0)
