// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"net/http"
	"sync"

	"code.cloudfoundry.org/app-autoscaler/src/autoscaler/api/brokerserver"
	"github.com/tedsuo/ifrit"
)

type FakeBrokerServer struct {
	CreateServerStub        func() (ifrit.Runner, error)
	createServerMutex       sync.RWMutex
	createServerArgsForCall []struct {
	}
	createServerReturns struct {
		result1 ifrit.Runner
		result2 error
	}
	createServerReturnsOnCall map[int]struct {
		result1 ifrit.Runner
		result2 error
	}
	GetRouterStub        func() (*http.ServeMux, error)
	getRouterMutex       sync.RWMutex
	getRouterArgsForCall []struct {
	}
	getRouterReturns struct {
		result1 *http.ServeMux
		result2 error
	}
	getRouterReturnsOnCall map[int]struct {
		result1 *http.ServeMux
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBrokerServer) CreateServer() (ifrit.Runner, error) {
	fake.createServerMutex.Lock()
	ret, specificReturn := fake.createServerReturnsOnCall[len(fake.createServerArgsForCall)]
	fake.createServerArgsForCall = append(fake.createServerArgsForCall, struct {
	}{})
	stub := fake.CreateServerStub
	fakeReturns := fake.createServerReturns
	fake.recordInvocation("CreateServer", []interface{}{})
	fake.createServerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBrokerServer) CreateServerCallCount() int {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	return len(fake.createServerArgsForCall)
}

func (fake *FakeBrokerServer) CreateServerCalls(stub func() (ifrit.Runner, error)) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = stub
}

func (fake *FakeBrokerServer) CreateServerReturns(result1 ifrit.Runner, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	fake.createServerReturns = struct {
		result1 ifrit.Runner
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerServer) CreateServerReturnsOnCall(i int, result1 ifrit.Runner, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	if fake.createServerReturnsOnCall == nil {
		fake.createServerReturnsOnCall = make(map[int]struct {
			result1 ifrit.Runner
			result2 error
		})
	}
	fake.createServerReturnsOnCall[i] = struct {
		result1 ifrit.Runner
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerServer) GetRouter() (*http.ServeMux, error) {
	fake.getRouterMutex.Lock()
	ret, specificReturn := fake.getRouterReturnsOnCall[len(fake.getRouterArgsForCall)]
	fake.getRouterArgsForCall = append(fake.getRouterArgsForCall, struct {
	}{})
	stub := fake.GetRouterStub
	fakeReturns := fake.getRouterReturns
	fake.recordInvocation("GetRouter", []interface{}{})
	fake.getRouterMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBrokerServer) GetRouterCallCount() int {
	fake.getRouterMutex.RLock()
	defer fake.getRouterMutex.RUnlock()
	return len(fake.getRouterArgsForCall)
}

func (fake *FakeBrokerServer) GetRouterCalls(stub func() (*http.ServeMux, error)) {
	fake.getRouterMutex.Lock()
	defer fake.getRouterMutex.Unlock()
	fake.GetRouterStub = stub
}

func (fake *FakeBrokerServer) GetRouterReturns(result1 *http.ServeMux, result2 error) {
	fake.getRouterMutex.Lock()
	defer fake.getRouterMutex.Unlock()
	fake.GetRouterStub = nil
	fake.getRouterReturns = struct {
		result1 *http.ServeMux
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerServer) GetRouterReturnsOnCall(i int, result1 *http.ServeMux, result2 error) {
	fake.getRouterMutex.Lock()
	defer fake.getRouterMutex.Unlock()
	fake.GetRouterStub = nil
	if fake.getRouterReturnsOnCall == nil {
		fake.getRouterReturnsOnCall = make(map[int]struct {
			result1 *http.ServeMux
			result2 error
		})
	}
	fake.getRouterReturnsOnCall[i] = struct {
		result1 *http.ServeMux
		result2 error
	}{result1, result2}
}

func (fake *FakeBrokerServer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBrokerServer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ brokerserver.BrokerServer = new(FakeBrokerServer)
