CREATE TABLE app_scaling_specific_date_schedule
(
    SCHEDULE_ID SERIAL PRIMARY KEY,
    APP_ID VARCHAR(50) NOT NULL,
    TIMEZONE VARCHAR(50) NOT NULL,
    START_DATE_TIME VARCHAR(50) NOT NULL,
    END_DATE_TIME VARCHAR(50) NOT NULL,
    INSTANCE_MIN_COUNT INTEGER NOT NULL,
    INSTANCE_MAX_COUNT INTEGER NOT NULL,
    DEFAULT_INSTANCE_MIN_COUNT INTEGER NOT NULL,
    DEFAULT_INSTANCE_MAX_COUNT INTEGER NOT NULL,
    INITIAL_MIN_INSTANCE_COUNT INTEGER,
    GUID VARCHAR(50) NOT NULL
);

CREATE TABLE app_scaling_recurring_schedule
(
    SCHEDULE_ID SERIAL PRIMARY KEY,
    APP_ID VARCHAR(50) NOT NULL,
    TIMEZONE VARCHAR(50) NOT NULL,
    DAYS_OF_WEEK INTEGER,
    DAYS_OF_MONTH INTEGER,
    START_DATE DATE,
    END_DATE DATE,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    INSTANCE_MIN_COUNT INTEGER NOT NULL,
    INSTANCE_MAX_COUNT INTEGER NOT NULL,
    DEFAULT_INSTANCE_MIN_COUNT INTEGER NOT NULL,
    DEFAULT_INSTANCE_MAX_COUNT INTEGER NOT NULL,
    INITIAL_MIN_INSTANCE_COUNT INTEGER,
    GUID VARCHAR(50) NOT NULL
);

CREATE TABLE app_scaling_active_schedule
(
    ID BIGINT NOT NULL,
    APP_ID VARCHAR(50) NOT NULL,
    START_JOB_IDENTIFIER BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT now(),
    INSTANCE_MIN_COUNT INTEGER NOT NULL,
    INSTANCE_MAX_COUNT INTEGER NOT NULL,
    INITIAL_MIN_INSTANCE_COUNT INTEGER,
    PRIMARY KEY(ID)
);

CREATE TABLE policy_json
(
    APP_ID VARCHAR(50) NOT NULL,
    POLICY_JSON JSON,
    GUID VARCHAR(50) NOT NULL
);

create index idx_app_id on app_scaling_specific_date_schedule(app_id);
create index idx_recurring_app_id on app_scaling_recurring_schedule(app_id);
create index idx_active_schedule_app_id on app_scaling_active_schedule(app_id);

commit;