---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

inputs:
- name: bbl-state
- name: ci
- name: app-autoscaler-mtar

params:
  CF_ORG: SAP_autoscaler_tests_OSS
  CF_SPACE: SAP_autoscaler_tests_OSS

run:
  path: ci/ci/infrastructure/scripts/deploy-metricsgateway.sh
