// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"autoscaler/db"
	"autoscaler/healthendpoint"
	"autoscaler/models"
	"sync"
	"time"

	"code.cloudfoundry.org/clock"
)

type FakeScalingEngineDB struct {
	SaveScalingHistoryStub        func(history *models.AppScalingHistory) error
	saveScalingHistoryMutex       sync.RWMutex
	saveScalingHistoryArgsForCall []struct {
		history *models.AppScalingHistory
	}
	saveScalingHistoryReturns struct {
		result1 error
	}
	saveScalingHistoryReturnsOnCall map[int]struct {
		result1 error
	}
	RetrieveScalingHistoriesStub        func(appId string, start int64, end int64, orderType db.OrderType, includeAll bool) ([]*models.AppScalingHistory, error)
	retrieveScalingHistoriesMutex       sync.RWMutex
	retrieveScalingHistoriesArgsForCall []struct {
		appId      string
		start      int64
		end        int64
		orderType  db.OrderType
		includeAll bool
	}
	retrieveScalingHistoriesReturns struct {
		result1 []*models.AppScalingHistory
		result2 error
	}
	retrieveScalingHistoriesReturnsOnCall map[int]struct {
		result1 []*models.AppScalingHistory
		result2 error
	}
	PruneScalingHistoriesStub        func(before int64) error
	pruneScalingHistoriesMutex       sync.RWMutex
	pruneScalingHistoriesArgsForCall []struct {
		before int64
	}
	pruneScalingHistoriesReturns struct {
		result1 error
	}
	pruneScalingHistoriesReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateScalingCooldownExpireTimeStub        func(appId string, expireAt int64) error
	updateScalingCooldownExpireTimeMutex       sync.RWMutex
	updateScalingCooldownExpireTimeArgsForCall []struct {
		appId    string
		expireAt int64
	}
	updateScalingCooldownExpireTimeReturns struct {
		result1 error
	}
	updateScalingCooldownExpireTimeReturnsOnCall map[int]struct {
		result1 error
	}
	CanScaleAppStub        func(appId string) (bool, int64, error)
	canScaleAppMutex       sync.RWMutex
	canScaleAppArgsForCall []struct {
		appId string
	}
	canScaleAppReturns struct {
		result1 bool
		result2 int64
		result3 error
	}
	canScaleAppReturnsOnCall map[int]struct {
		result1 bool
		result2 int64
		result3 error
	}
	GetActiveScheduleStub        func(appId string) (*models.ActiveSchedule, error)
	getActiveScheduleMutex       sync.RWMutex
	getActiveScheduleArgsForCall []struct {
		appId string
	}
	getActiveScheduleReturns struct {
		result1 *models.ActiveSchedule
		result2 error
	}
	getActiveScheduleReturnsOnCall map[int]struct {
		result1 *models.ActiveSchedule
		result2 error
	}
	GetActiveSchedulesStub        func() (map[string]string, error)
	getActiveSchedulesMutex       sync.RWMutex
	getActiveSchedulesArgsForCall []struct{}
	getActiveSchedulesReturns     struct {
		result1 map[string]string
		result2 error
	}
	getActiveSchedulesReturnsOnCall map[int]struct {
		result1 map[string]string
		result2 error
	}
	SetActiveScheduleStub        func(appId string, schedule *models.ActiveSchedule) error
	setActiveScheduleMutex       sync.RWMutex
	setActiveScheduleArgsForCall []struct {
		appId    string
		schedule *models.ActiveSchedule
	}
	setActiveScheduleReturns struct {
		result1 error
	}
	setActiveScheduleReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveActiveScheduleStub        func(appId string) error
	removeActiveScheduleMutex       sync.RWMutex
	removeActiveScheduleArgsForCall []struct {
		appId string
	}
	removeActiveScheduleReturns struct {
		result1 error
	}
	removeActiveScheduleReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct{}
	closeReturns     struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	EmitHealthMetricsStub        func(h healthendpoint.Health, cclock clock.Clock, interval time.Duration)
	emitHealthMetricsMutex       sync.RWMutex
	emitHealthMetricsArgsForCall []struct {
		h        healthendpoint.Health
		cclock   clock.Clock
		interval time.Duration
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeScalingEngineDB) SaveScalingHistory(history *models.AppScalingHistory) error {
	fake.saveScalingHistoryMutex.Lock()
	ret, specificReturn := fake.saveScalingHistoryReturnsOnCall[len(fake.saveScalingHistoryArgsForCall)]
	fake.saveScalingHistoryArgsForCall = append(fake.saveScalingHistoryArgsForCall, struct {
		history *models.AppScalingHistory
	}{history})
	fake.recordInvocation("SaveScalingHistory", []interface{}{history})
	fake.saveScalingHistoryMutex.Unlock()
	if fake.SaveScalingHistoryStub != nil {
		return fake.SaveScalingHistoryStub(history)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.saveScalingHistoryReturns.result1
}

func (fake *FakeScalingEngineDB) SaveScalingHistoryCallCount() int {
	fake.saveScalingHistoryMutex.RLock()
	defer fake.saveScalingHistoryMutex.RUnlock()
	return len(fake.saveScalingHistoryArgsForCall)
}

func (fake *FakeScalingEngineDB) SaveScalingHistoryArgsForCall(i int) *models.AppScalingHistory {
	fake.saveScalingHistoryMutex.RLock()
	defer fake.saveScalingHistoryMutex.RUnlock()
	return fake.saveScalingHistoryArgsForCall[i].history
}

func (fake *FakeScalingEngineDB) SaveScalingHistoryReturns(result1 error) {
	fake.SaveScalingHistoryStub = nil
	fake.saveScalingHistoryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) SaveScalingHistoryReturnsOnCall(i int, result1 error) {
	fake.SaveScalingHistoryStub = nil
	if fake.saveScalingHistoryReturnsOnCall == nil {
		fake.saveScalingHistoryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveScalingHistoryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) RetrieveScalingHistories(appId string, start int64, end int64, orderType db.OrderType, includeAll bool) ([]*models.AppScalingHistory, error) {
	fake.retrieveScalingHistoriesMutex.Lock()
	ret, specificReturn := fake.retrieveScalingHistoriesReturnsOnCall[len(fake.retrieveScalingHistoriesArgsForCall)]
	fake.retrieveScalingHistoriesArgsForCall = append(fake.retrieveScalingHistoriesArgsForCall, struct {
		appId      string
		start      int64
		end        int64
		orderType  db.OrderType
		includeAll bool
	}{appId, start, end, orderType, includeAll})
	fake.recordInvocation("RetrieveScalingHistories", []interface{}{appId, start, end, orderType, includeAll})
	fake.retrieveScalingHistoriesMutex.Unlock()
	if fake.RetrieveScalingHistoriesStub != nil {
		return fake.RetrieveScalingHistoriesStub(appId, start, end, orderType, includeAll)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.retrieveScalingHistoriesReturns.result1, fake.retrieveScalingHistoriesReturns.result2
}

func (fake *FakeScalingEngineDB) RetrieveScalingHistoriesCallCount() int {
	fake.retrieveScalingHistoriesMutex.RLock()
	defer fake.retrieveScalingHistoriesMutex.RUnlock()
	return len(fake.retrieveScalingHistoriesArgsForCall)
}

func (fake *FakeScalingEngineDB) RetrieveScalingHistoriesArgsForCall(i int) (string, int64, int64, db.OrderType, bool) {
	fake.retrieveScalingHistoriesMutex.RLock()
	defer fake.retrieveScalingHistoriesMutex.RUnlock()
	return fake.retrieveScalingHistoriesArgsForCall[i].appId, fake.retrieveScalingHistoriesArgsForCall[i].start, fake.retrieveScalingHistoriesArgsForCall[i].end, fake.retrieveScalingHistoriesArgsForCall[i].orderType, fake.retrieveScalingHistoriesArgsForCall[i].includeAll
}

func (fake *FakeScalingEngineDB) RetrieveScalingHistoriesReturns(result1 []*models.AppScalingHistory, result2 error) {
	fake.RetrieveScalingHistoriesStub = nil
	fake.retrieveScalingHistoriesReturns = struct {
		result1 []*models.AppScalingHistory
		result2 error
	}{result1, result2}
}

func (fake *FakeScalingEngineDB) RetrieveScalingHistoriesReturnsOnCall(i int, result1 []*models.AppScalingHistory, result2 error) {
	fake.RetrieveScalingHistoriesStub = nil
	if fake.retrieveScalingHistoriesReturnsOnCall == nil {
		fake.retrieveScalingHistoriesReturnsOnCall = make(map[int]struct {
			result1 []*models.AppScalingHistory
			result2 error
		})
	}
	fake.retrieveScalingHistoriesReturnsOnCall[i] = struct {
		result1 []*models.AppScalingHistory
		result2 error
	}{result1, result2}
}

func (fake *FakeScalingEngineDB) PruneScalingHistories(before int64) error {
	fake.pruneScalingHistoriesMutex.Lock()
	ret, specificReturn := fake.pruneScalingHistoriesReturnsOnCall[len(fake.pruneScalingHistoriesArgsForCall)]
	fake.pruneScalingHistoriesArgsForCall = append(fake.pruneScalingHistoriesArgsForCall, struct {
		before int64
	}{before})
	fake.recordInvocation("PruneScalingHistories", []interface{}{before})
	fake.pruneScalingHistoriesMutex.Unlock()
	if fake.PruneScalingHistoriesStub != nil {
		return fake.PruneScalingHistoriesStub(before)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.pruneScalingHistoriesReturns.result1
}

func (fake *FakeScalingEngineDB) PruneScalingHistoriesCallCount() int {
	fake.pruneScalingHistoriesMutex.RLock()
	defer fake.pruneScalingHistoriesMutex.RUnlock()
	return len(fake.pruneScalingHistoriesArgsForCall)
}

func (fake *FakeScalingEngineDB) PruneScalingHistoriesArgsForCall(i int) int64 {
	fake.pruneScalingHistoriesMutex.RLock()
	defer fake.pruneScalingHistoriesMutex.RUnlock()
	return fake.pruneScalingHistoriesArgsForCall[i].before
}

func (fake *FakeScalingEngineDB) PruneScalingHistoriesReturns(result1 error) {
	fake.PruneScalingHistoriesStub = nil
	fake.pruneScalingHistoriesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) PruneScalingHistoriesReturnsOnCall(i int, result1 error) {
	fake.PruneScalingHistoriesStub = nil
	if fake.pruneScalingHistoriesReturnsOnCall == nil {
		fake.pruneScalingHistoriesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pruneScalingHistoriesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) UpdateScalingCooldownExpireTime(appId string, expireAt int64) error {
	fake.updateScalingCooldownExpireTimeMutex.Lock()
	ret, specificReturn := fake.updateScalingCooldownExpireTimeReturnsOnCall[len(fake.updateScalingCooldownExpireTimeArgsForCall)]
	fake.updateScalingCooldownExpireTimeArgsForCall = append(fake.updateScalingCooldownExpireTimeArgsForCall, struct {
		appId    string
		expireAt int64
	}{appId, expireAt})
	fake.recordInvocation("UpdateScalingCooldownExpireTime", []interface{}{appId, expireAt})
	fake.updateScalingCooldownExpireTimeMutex.Unlock()
	if fake.UpdateScalingCooldownExpireTimeStub != nil {
		return fake.UpdateScalingCooldownExpireTimeStub(appId, expireAt)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.updateScalingCooldownExpireTimeReturns.result1
}

func (fake *FakeScalingEngineDB) UpdateScalingCooldownExpireTimeCallCount() int {
	fake.updateScalingCooldownExpireTimeMutex.RLock()
	defer fake.updateScalingCooldownExpireTimeMutex.RUnlock()
	return len(fake.updateScalingCooldownExpireTimeArgsForCall)
}

func (fake *FakeScalingEngineDB) UpdateScalingCooldownExpireTimeArgsForCall(i int) (string, int64) {
	fake.updateScalingCooldownExpireTimeMutex.RLock()
	defer fake.updateScalingCooldownExpireTimeMutex.RUnlock()
	return fake.updateScalingCooldownExpireTimeArgsForCall[i].appId, fake.updateScalingCooldownExpireTimeArgsForCall[i].expireAt
}

func (fake *FakeScalingEngineDB) UpdateScalingCooldownExpireTimeReturns(result1 error) {
	fake.UpdateScalingCooldownExpireTimeStub = nil
	fake.updateScalingCooldownExpireTimeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) UpdateScalingCooldownExpireTimeReturnsOnCall(i int, result1 error) {
	fake.UpdateScalingCooldownExpireTimeStub = nil
	if fake.updateScalingCooldownExpireTimeReturnsOnCall == nil {
		fake.updateScalingCooldownExpireTimeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateScalingCooldownExpireTimeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) CanScaleApp(appId string) (bool, int64, error) {
	fake.canScaleAppMutex.Lock()
	ret, specificReturn := fake.canScaleAppReturnsOnCall[len(fake.canScaleAppArgsForCall)]
	fake.canScaleAppArgsForCall = append(fake.canScaleAppArgsForCall, struct {
		appId string
	}{appId})
	fake.recordInvocation("CanScaleApp", []interface{}{appId})
	fake.canScaleAppMutex.Unlock()
	if fake.CanScaleAppStub != nil {
		return fake.CanScaleAppStub(appId)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.canScaleAppReturns.result1, fake.canScaleAppReturns.result2, fake.canScaleAppReturns.result3
}

func (fake *FakeScalingEngineDB) CanScaleAppCallCount() int {
	fake.canScaleAppMutex.RLock()
	defer fake.canScaleAppMutex.RUnlock()
	return len(fake.canScaleAppArgsForCall)
}

func (fake *FakeScalingEngineDB) CanScaleAppArgsForCall(i int) string {
	fake.canScaleAppMutex.RLock()
	defer fake.canScaleAppMutex.RUnlock()
	return fake.canScaleAppArgsForCall[i].appId
}

func (fake *FakeScalingEngineDB) CanScaleAppReturns(result1 bool, result2 int64, result3 error) {
	fake.CanScaleAppStub = nil
	fake.canScaleAppReturns = struct {
		result1 bool
		result2 int64
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeScalingEngineDB) CanScaleAppReturnsOnCall(i int, result1 bool, result2 int64, result3 error) {
	fake.CanScaleAppStub = nil
	if fake.canScaleAppReturnsOnCall == nil {
		fake.canScaleAppReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 int64
			result3 error
		})
	}
	fake.canScaleAppReturnsOnCall[i] = struct {
		result1 bool
		result2 int64
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeScalingEngineDB) GetActiveSchedule(appId string) (*models.ActiveSchedule, error) {
	fake.getActiveScheduleMutex.Lock()
	ret, specificReturn := fake.getActiveScheduleReturnsOnCall[len(fake.getActiveScheduleArgsForCall)]
	fake.getActiveScheduleArgsForCall = append(fake.getActiveScheduleArgsForCall, struct {
		appId string
	}{appId})
	fake.recordInvocation("GetActiveSchedule", []interface{}{appId})
	fake.getActiveScheduleMutex.Unlock()
	if fake.GetActiveScheduleStub != nil {
		return fake.GetActiveScheduleStub(appId)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getActiveScheduleReturns.result1, fake.getActiveScheduleReturns.result2
}

func (fake *FakeScalingEngineDB) GetActiveScheduleCallCount() int {
	fake.getActiveScheduleMutex.RLock()
	defer fake.getActiveScheduleMutex.RUnlock()
	return len(fake.getActiveScheduleArgsForCall)
}

func (fake *FakeScalingEngineDB) GetActiveScheduleArgsForCall(i int) string {
	fake.getActiveScheduleMutex.RLock()
	defer fake.getActiveScheduleMutex.RUnlock()
	return fake.getActiveScheduleArgsForCall[i].appId
}

func (fake *FakeScalingEngineDB) GetActiveScheduleReturns(result1 *models.ActiveSchedule, result2 error) {
	fake.GetActiveScheduleStub = nil
	fake.getActiveScheduleReturns = struct {
		result1 *models.ActiveSchedule
		result2 error
	}{result1, result2}
}

func (fake *FakeScalingEngineDB) GetActiveScheduleReturnsOnCall(i int, result1 *models.ActiveSchedule, result2 error) {
	fake.GetActiveScheduleStub = nil
	if fake.getActiveScheduleReturnsOnCall == nil {
		fake.getActiveScheduleReturnsOnCall = make(map[int]struct {
			result1 *models.ActiveSchedule
			result2 error
		})
	}
	fake.getActiveScheduleReturnsOnCall[i] = struct {
		result1 *models.ActiveSchedule
		result2 error
	}{result1, result2}
}

func (fake *FakeScalingEngineDB) GetActiveSchedules() (map[string]string, error) {
	fake.getActiveSchedulesMutex.Lock()
	ret, specificReturn := fake.getActiveSchedulesReturnsOnCall[len(fake.getActiveSchedulesArgsForCall)]
	fake.getActiveSchedulesArgsForCall = append(fake.getActiveSchedulesArgsForCall, struct{}{})
	fake.recordInvocation("GetActiveSchedules", []interface{}{})
	fake.getActiveSchedulesMutex.Unlock()
	if fake.GetActiveSchedulesStub != nil {
		return fake.GetActiveSchedulesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getActiveSchedulesReturns.result1, fake.getActiveSchedulesReturns.result2
}

func (fake *FakeScalingEngineDB) GetActiveSchedulesCallCount() int {
	fake.getActiveSchedulesMutex.RLock()
	defer fake.getActiveSchedulesMutex.RUnlock()
	return len(fake.getActiveSchedulesArgsForCall)
}

func (fake *FakeScalingEngineDB) GetActiveSchedulesReturns(result1 map[string]string, result2 error) {
	fake.GetActiveSchedulesStub = nil
	fake.getActiveSchedulesReturns = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeScalingEngineDB) GetActiveSchedulesReturnsOnCall(i int, result1 map[string]string, result2 error) {
	fake.GetActiveSchedulesStub = nil
	if fake.getActiveSchedulesReturnsOnCall == nil {
		fake.getActiveSchedulesReturnsOnCall = make(map[int]struct {
			result1 map[string]string
			result2 error
		})
	}
	fake.getActiveSchedulesReturnsOnCall[i] = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeScalingEngineDB) SetActiveSchedule(appId string, schedule *models.ActiveSchedule) error {
	fake.setActiveScheduleMutex.Lock()
	ret, specificReturn := fake.setActiveScheduleReturnsOnCall[len(fake.setActiveScheduleArgsForCall)]
	fake.setActiveScheduleArgsForCall = append(fake.setActiveScheduleArgsForCall, struct {
		appId    string
		schedule *models.ActiveSchedule
	}{appId, schedule})
	fake.recordInvocation("SetActiveSchedule", []interface{}{appId, schedule})
	fake.setActiveScheduleMutex.Unlock()
	if fake.SetActiveScheduleStub != nil {
		return fake.SetActiveScheduleStub(appId, schedule)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.setActiveScheduleReturns.result1
}

func (fake *FakeScalingEngineDB) SetActiveScheduleCallCount() int {
	fake.setActiveScheduleMutex.RLock()
	defer fake.setActiveScheduleMutex.RUnlock()
	return len(fake.setActiveScheduleArgsForCall)
}

func (fake *FakeScalingEngineDB) SetActiveScheduleArgsForCall(i int) (string, *models.ActiveSchedule) {
	fake.setActiveScheduleMutex.RLock()
	defer fake.setActiveScheduleMutex.RUnlock()
	return fake.setActiveScheduleArgsForCall[i].appId, fake.setActiveScheduleArgsForCall[i].schedule
}

func (fake *FakeScalingEngineDB) SetActiveScheduleReturns(result1 error) {
	fake.SetActiveScheduleStub = nil
	fake.setActiveScheduleReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) SetActiveScheduleReturnsOnCall(i int, result1 error) {
	fake.SetActiveScheduleStub = nil
	if fake.setActiveScheduleReturnsOnCall == nil {
		fake.setActiveScheduleReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setActiveScheduleReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) RemoveActiveSchedule(appId string) error {
	fake.removeActiveScheduleMutex.Lock()
	ret, specificReturn := fake.removeActiveScheduleReturnsOnCall[len(fake.removeActiveScheduleArgsForCall)]
	fake.removeActiveScheduleArgsForCall = append(fake.removeActiveScheduleArgsForCall, struct {
		appId string
	}{appId})
	fake.recordInvocation("RemoveActiveSchedule", []interface{}{appId})
	fake.removeActiveScheduleMutex.Unlock()
	if fake.RemoveActiveScheduleStub != nil {
		return fake.RemoveActiveScheduleStub(appId)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.removeActiveScheduleReturns.result1
}

func (fake *FakeScalingEngineDB) RemoveActiveScheduleCallCount() int {
	fake.removeActiveScheduleMutex.RLock()
	defer fake.removeActiveScheduleMutex.RUnlock()
	return len(fake.removeActiveScheduleArgsForCall)
}

func (fake *FakeScalingEngineDB) RemoveActiveScheduleArgsForCall(i int) string {
	fake.removeActiveScheduleMutex.RLock()
	defer fake.removeActiveScheduleMutex.RUnlock()
	return fake.removeActiveScheduleArgsForCall[i].appId
}

func (fake *FakeScalingEngineDB) RemoveActiveScheduleReturns(result1 error) {
	fake.RemoveActiveScheduleStub = nil
	fake.removeActiveScheduleReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) RemoveActiveScheduleReturnsOnCall(i int, result1 error) {
	fake.RemoveActiveScheduleStub = nil
	if fake.removeActiveScheduleReturnsOnCall == nil {
		fake.removeActiveScheduleReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeActiveScheduleReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct{}{})
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		return fake.CloseStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.closeReturns.result1
}

func (fake *FakeScalingEngineDB) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeScalingEngineDB) CloseReturns(result1 error) {
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) CloseReturnsOnCall(i int, result1 error) {
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeScalingEngineDB) EmitHealthMetrics(h healthendpoint.Health, cclock clock.Clock, interval time.Duration) {
	fake.emitHealthMetricsMutex.Lock()
	fake.emitHealthMetricsArgsForCall = append(fake.emitHealthMetricsArgsForCall, struct {
		h        healthendpoint.Health
		cclock   clock.Clock
		interval time.Duration
	}{h, cclock, interval})
	fake.recordInvocation("EmitHealthMetrics", []interface{}{h, cclock, interval})
	fake.emitHealthMetricsMutex.Unlock()
	if fake.EmitHealthMetricsStub != nil {
		fake.EmitHealthMetricsStub(h, cclock, interval)
	}
}

func (fake *FakeScalingEngineDB) EmitHealthMetricsCallCount() int {
	fake.emitHealthMetricsMutex.RLock()
	defer fake.emitHealthMetricsMutex.RUnlock()
	return len(fake.emitHealthMetricsArgsForCall)
}

func (fake *FakeScalingEngineDB) EmitHealthMetricsArgsForCall(i int) (healthendpoint.Health, clock.Clock, time.Duration) {
	fake.emitHealthMetricsMutex.RLock()
	defer fake.emitHealthMetricsMutex.RUnlock()
	return fake.emitHealthMetricsArgsForCall[i].h, fake.emitHealthMetricsArgsForCall[i].cclock, fake.emitHealthMetricsArgsForCall[i].interval
}

func (fake *FakeScalingEngineDB) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.saveScalingHistoryMutex.RLock()
	defer fake.saveScalingHistoryMutex.RUnlock()
	fake.retrieveScalingHistoriesMutex.RLock()
	defer fake.retrieveScalingHistoriesMutex.RUnlock()
	fake.pruneScalingHistoriesMutex.RLock()
	defer fake.pruneScalingHistoriesMutex.RUnlock()
	fake.updateScalingCooldownExpireTimeMutex.RLock()
	defer fake.updateScalingCooldownExpireTimeMutex.RUnlock()
	fake.canScaleAppMutex.RLock()
	defer fake.canScaleAppMutex.RUnlock()
	fake.getActiveScheduleMutex.RLock()
	defer fake.getActiveScheduleMutex.RUnlock()
	fake.getActiveSchedulesMutex.RLock()
	defer fake.getActiveSchedulesMutex.RUnlock()
	fake.setActiveScheduleMutex.RLock()
	defer fake.setActiveScheduleMutex.RUnlock()
	fake.removeActiveScheduleMutex.RLock()
	defer fake.removeActiveScheduleMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.emitHealthMetricsMutex.RLock()
	defer fake.emitHealthMetricsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeScalingEngineDB) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.ScalingEngineDB = new(FakeScalingEngineDB)
