// This file was generated by counterfeiter
package fakes

import (
	"autoscaler/db"
	"autoscaler/models"
	"sync"
)

type FakeSchedulerDB struct {
	GetActiveSchedulesStub        func() (map[string]*models.ActiveSchedule, error)
	getActiveSchedulesMutex       sync.RWMutex
	getActiveSchedulesArgsForCall []struct{}
	getActiveSchedulesReturns     struct {
		result1 map[string]*models.ActiveSchedule
		result2 error
	}
	SynchronizeActiveSchedulesStub        func(map[string]bool) error
	synchronizeActiveSchedulesMutex       sync.RWMutex
	synchronizeActiveSchedulesArgsForCall []struct {
		arg1 map[string]bool
	}
	synchronizeActiveSchedulesReturns struct {
		result1 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct{}
	closeReturns     struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSchedulerDB) GetActiveSchedules() (map[string]*models.ActiveSchedule, error) {
	fake.getActiveSchedulesMutex.Lock()
	fake.getActiveSchedulesArgsForCall = append(fake.getActiveSchedulesArgsForCall, struct{}{})
	fake.recordInvocation("GetActiveSchedules", []interface{}{})
	fake.getActiveSchedulesMutex.Unlock()
	if fake.GetActiveSchedulesStub != nil {
		return fake.GetActiveSchedulesStub()
	}
	return fake.getActiveSchedulesReturns.result1, fake.getActiveSchedulesReturns.result2
}

func (fake *FakeSchedulerDB) GetActiveSchedulesCallCount() int {
	fake.getActiveSchedulesMutex.RLock()
	defer fake.getActiveSchedulesMutex.RUnlock()
	return len(fake.getActiveSchedulesArgsForCall)
}

func (fake *FakeSchedulerDB) GetActiveSchedulesReturns(result1 map[string]*models.ActiveSchedule, result2 error) {
	fake.GetActiveSchedulesStub = nil
	fake.getActiveSchedulesReturns = struct {
		result1 map[string]*models.ActiveSchedule
		result2 error
	}{result1, result2}
}

func (fake *FakeSchedulerDB) SynchronizeActiveSchedules(arg1 map[string]bool) error {
	fake.synchronizeActiveSchedulesMutex.Lock()
	fake.synchronizeActiveSchedulesArgsForCall = append(fake.synchronizeActiveSchedulesArgsForCall, struct {
		arg1 map[string]bool
	}{arg1})
	fake.recordInvocation("SynchronizeActiveSchedules", []interface{}{arg1})
	fake.synchronizeActiveSchedulesMutex.Unlock()
	if fake.SynchronizeActiveSchedulesStub != nil {
		return fake.SynchronizeActiveSchedulesStub(arg1)
	}
	return fake.synchronizeActiveSchedulesReturns.result1
}

func (fake *FakeSchedulerDB) SynchronizeActiveSchedulesCallCount() int {
	fake.synchronizeActiveSchedulesMutex.RLock()
	defer fake.synchronizeActiveSchedulesMutex.RUnlock()
	return len(fake.synchronizeActiveSchedulesArgsForCall)
}

func (fake *FakeSchedulerDB) SynchronizeActiveSchedulesArgsForCall(i int) map[string]bool {
	fake.synchronizeActiveSchedulesMutex.RLock()
	defer fake.synchronizeActiveSchedulesMutex.RUnlock()
	return fake.synchronizeActiveSchedulesArgsForCall[i].arg1
}

func (fake *FakeSchedulerDB) SynchronizeActiveSchedulesReturns(result1 error) {
	fake.SynchronizeActiveSchedulesStub = nil
	fake.synchronizeActiveSchedulesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSchedulerDB) Close() error {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct{}{})
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		return fake.CloseStub()
	}
	return fake.closeReturns.result1
}

func (fake *FakeSchedulerDB) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeSchedulerDB) CloseReturns(result1 error) {
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSchedulerDB) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getActiveSchedulesMutex.RLock()
	defer fake.getActiveSchedulesMutex.RUnlock()
	fake.synchronizeActiveSchedulesMutex.RLock()
	defer fake.synchronizeActiveSchedulesMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeSchedulerDB) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.SchedulerDB = new(FakeSchedulerDB)
