/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:10 CST 2016
 */

package org.cloudfoundry.autoscaler.api.nls;

public class APIServerMessages extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_API_Server_retrieve_service_information_context", "API Server retrieving service information" },
      { "RestResponseErrorMsg_Create_Update_Policy_context", "Create/Update Policy" },
      { "RestResponseErrorMsg_Enable_Policy_context", "Enable Policy" },
      { "RestResponseErrorMsg_Get_Metric_Data_context", "Get Metric Data" },
      { "RestResponseErrorMsg_Get_Policy_context", "Get Policy" },
      { "RestResponseErrorMsg_Get_Scaling_History_context", "Get Scaling History" },
      { "RestResponseErrorMsg_app_info_not_found_error", "CWSCV6008E: The following error occurred when retrieving information for application {0}: {1}." },
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV6007E: The application is not found: {0}." },
      { "RestResponseErrorMsg_attach_policy_in_Create_Policy_context", "attaching policy in Create/Update Policy API" },
      { "RestResponseErrorMsg_cloud_error", "CWSCV6006E: Calling CloudFoundry APIs failed: {0}." },
      { "RestResponseErrorMsg_create_policy_in_Create_Policy_context", "creating policy in Create/Update Policy API" },
      { "RestResponseErrorMsg_delete_policy_in_Delete_Policy_context", "deleting policy in Delete Policy API" },
      { "RestResponseErrorMsg_detach_policy_in_Delete_Policy_context", "detaching policy in Create/Update Policy API" },
      { "RestResponseErrorMsg_enable_policy_in_Enable_Policy_context", "enabling policy in Enable Policy API" },
      { "RestResponseErrorMsg_get_history_in_Get_History_context", "getting history in Get History API" },
      { "RestResponseErrorMsg_get_metric_in_Get_Metric_context", "getting metric in Get Metric API" },
      { "RestResponseErrorMsg_get_policy_in_Get_Policy_context", "getting policy in Get Policy API" },
      { "RestResponseErrorMsg_input_json_format_error", "CWSCV6003E: Input JSON strings format error: {0} in the input JSON for API: {1}." },
      { "RestResponseErrorMsg_input_json_format_location_error", "CWSCV6012E: Format error at line {1} column {2} in the input JSON strings for API: {0}." },
      { "RestResponseErrorMsg_input_json_parse_error", "CWSCV6001E: The API server cannot parse the input JSON strings for API: {0}." },
      { "RestResponseErrorMsg_internal_authentication_failed_error", "CWSCV6011E: Internal Authentication failed during {0}." },
      { "RestResponseErrorMsg_internal_server_error", "CWSCV6005E: Internal server error occurred during {0}." },
      { "RestResponseErrorMsg_output_json_format_error", "CWSCV6004E: Output JSON strings format error: {0} in the output JSON for API: {1}." },
      { "RestResponseErrorMsg_output_json_parse_error", "CWSCV6002E: The API server cannot parse the output JSON strings for API: {0}." },
      { "RestResponseErrorMsg_parse_input_json_context", "parse input JSON" },
      { "RestResponseErrorMsg_policy_not_exist_error", "CWSCV6010E: Policy for App {0} is not found." },
      { "RestResponseErrorMsg_retrieve_application_service_information_context", "retrieve application service information" },
      { "RestResponseErrorMsg_retrieve_org_sapce_information_context", "retrieve org/space information" },
      { "RestResponseErrorMsg_service_not_found_error", "CWSCV6009E: Service: {0} for App {1} is not found." },
      { "RestResponseErrorMsg_update_policy_in_Create_Policy_context", "updating policy in Create/Update Policy API" }
   };
}
