/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:10 CST 2016
 */

package org.cloudfoundry.autoscaler.api.nls;

public class APIServerMessages_ko extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_API_Server_retrieve_service_information_context", "\uc11c\ube44\uc2a4 \uc815\ubcf4\ub97c \uac80\uc0c9\ud558\ub294 API \uc11c\ubc84" },
      { "RestResponseErrorMsg_Create_Update_Policy_context", "\uc815\ucc45 \uc791\uc131/\uc5c5\ub370\uc774\ud2b8" },
      { "RestResponseErrorMsg_Enable_Policy_context", "\uc815\ucc45 \uc0ac\uc6a9" },
      { "RestResponseErrorMsg_Get_Metric_Data_context", "\uba54\ud2b8\ub9ad \ub370\uc774\ud130 \uac00\uc838\uc624\uae30" },
      { "RestResponseErrorMsg_Get_Policy_context", "\uc815\ucc45 \uac00\uc838\uc624\uae30" },
      { "RestResponseErrorMsg_Get_Scaling_History_context", "\uc2a4\ucf00\uc77c\ub9c1 \ud788\uc2a4\ud1a0\ub9ac \uac00\uc838\uc624\uae30" },
      { "RestResponseErrorMsg_app_info_not_found_error", "CWSCV6008E: {0} \uc560\ud50c\ub9ac\ucf00\uc774\uc158\uc5d0 \ub300\ud55c \uc815\ubcf4\ub97c \uac80\uc0c9\ud558\ub294 \uc911\uc5d0 \ub2e4\uc74c \uc624\ub958 \ubc1c\uc0dd: {1}." },
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV6007E: \uc560\ud50c\ub9ac\ucf00\uc774\uc158\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc74c: {0}" },
      { "RestResponseErrorMsg_attach_policy_in_Create_Policy_context", "\uc815\ucc45 \uc791\uc131/\uc5c5\ub370\uc774\ud2b8 API\uc5d0\uc11c \uc815\ucc45 \ucca8\ubd80" },
      { "RestResponseErrorMsg_cloud_error", "CWSCV6006E: CloudFoundry API \ud638\ucd9c \uc2e4\ud328: {0}" },
      { "RestResponseErrorMsg_create_policy_in_Create_Policy_context", "\uc815\ucc45 \uc791\uc131/\uc5c5\ub370\uc774\ud2b8 API\uc5d0\uc11c \uc815\ucc45 \uc791\uc131" },
      { "RestResponseErrorMsg_delete_policy_in_Delete_Policy_context", "\uc815\ucc45 \uc0ad\uc81c API\uc5d0\uc11c \uc815\ucc45 \uc0ad\uc81c" },
      { "RestResponseErrorMsg_detach_policy_in_Delete_Policy_context", "\uc815\ucc45 \uc791\uc131/\uc5c5\ub370\uc774\ud2b8 API\uc5d0\uc11c \uc815\ucc45 \ubd84\ub9ac" },
      { "RestResponseErrorMsg_enable_policy_in_Enable_Policy_context", "\uc815\ucc45 \uc0ac\uc6a9 API\uc5d0\uc11c \uc815\ucc45\uc744 \uc0ac\uc6a9\uc73c\ub85c \uc124\uc815" },
      { "RestResponseErrorMsg_get_history_in_Get_History_context", "\ud788\uc2a4\ud1a0\ub9ac \uac00\uc838\uc624\uae30 API\uc5d0\uc11c \ud788\uc2a4\ud1a0\ub9ac \uac00\uc838\uc624\uae30" },
      { "RestResponseErrorMsg_get_metric_in_Get_Metric_context", "\uba54\ud2b8\ub9ad \uac00\uc838\uc624\uae30 API\uc5d0\uc11c \uba54\ud2b8\ub9ad \uac00\uc838\uc624\uae30" },
      { "RestResponseErrorMsg_get_policy_in_Get_Policy_context", "\uc815\ucc45 \uac00\uc838\uc624\uae30 API\uc5d0\uc11c \uc815\ucc45 \uac00\uc838\uc624\uae30" },
      { "RestResponseErrorMsg_input_json_format_error", "CWSCV6003E: \uc785\ub825 JSON \ubb38\uc790\uc5f4 \ud615\uc2dd \uc624\ub958: API\uc5d0 \ub300\ud55c \uc785\ub825 JSON\uc758 {0}: {1}." },
      { "RestResponseErrorMsg_input_json_format_location_error", "CWSCV6012E: API\uc758 \uc785\ub825 JSON \ubb38\uc790\uc5f4 {1} \ud589 {2} \uc5f4\uc5d0\uc11c \ud615\uc2dd \uc624\ub958: {0}." },
      { "RestResponseErrorMsg_input_json_parse_error", "CWSCV6001E: API \uc11c\ubc84\uac00 API\uc5d0 \ub300\ud55c \uc785\ub825 JSON \ubb38\uc790\uc5f4\uc744 \uad6c\ubb38 \ubd84\uc11d\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4. {0}" },
      { "RestResponseErrorMsg_internal_authentication_failed_error", "CWSCV6011E: {0} \uc911\uc5d0 \ub0b4\ubd80 \uc778\uc99d\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4." },
      { "RestResponseErrorMsg_internal_server_error", "CWSCV6005E: {0} \uc911\uc5d0 \ub0b4\ubd80 \uc11c\ubc84 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4." },
      { "RestResponseErrorMsg_output_json_format_error", "CWSCV6004E: \ucd9c\ub825 JSON \ubb38\uc790\uc5f4 \ud615\uc2dd \uc624\ub958: API\uc5d0 \ub300\ud55c \ucd9c\ub825 JSON\uc758 {0}: {1}." },
      { "RestResponseErrorMsg_output_json_parse_error", "CWSCV6002E: API \uc11c\ubc84\uac00 API\uc5d0 \ub300\ud55c \ucd9c\ub825 JSON \ubb38\uc790\uc5f4\uc744 \uad6c\ubb38 \ubd84\uc11d\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4. {0}" },
      { "RestResponseErrorMsg_parse_input_json_context", "\uc785\ub825 JSON \uad6c\ubb38 \ubd84\uc11d" },
      { "RestResponseErrorMsg_policy_not_exist_error", "CWSCV6010E: {0} \uc571\uc5d0 \ub300\ud55c \uc815\ucc45\uc744 \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4." },
      { "RestResponseErrorMsg_retrieve_application_service_information_context", "\uc560\ud50c\ub9ac\ucf00\uc774\uc158 \uc11c\ube44\uc2a4 \uc815\ubcf4 \uac80\uc0c9" },
      { "RestResponseErrorMsg_retrieve_org_sapce_information_context", "\uc870\uc9c1/\uacf5\uac04 \uc815\ubcf4 \uac80\uc0c9" },
      { "RestResponseErrorMsg_service_not_found_error", "CWSCV6009E: {1} \uc571\uc5d0 \ub300\ud55c {0} \uc11c\ube44\uc2a4\ub97c \ucc3e\uc744 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4." },
      { "RestResponseErrorMsg_update_policy_in_Create_Policy_context", "\uc815\ucc45 \uc791\uc131/\uc5c5\ub370\uc774\ud2b8 API\uc5d0\uc11c \uc815\ucc45 \uc5c5\ub370\uc774\ud2b8" }
   };
}
