/**
 * WARNING!  THIS FILE IS AUTOMATICALLY GENERATED!  DO NOT MODIFY IT!
 * Generated on Fri Feb 26 16:36:10 CST 2016
 */

package org.cloudfoundry.autoscaler.api.nls;

public class APIServerMessages_pt extends java.util.ListResourceBundle
{
   public Object[][] getContents() {
       return resources;
   }
   private final static Object[][] resources= {
      { "RestResponseErrorMsg_API_Server_retrieve_service_information_context", "Servidor API recuperando informa\u00e7\u00f5es de servi\u00e7o" },
      { "RestResponseErrorMsg_Create_Update_Policy_context", "Criar/Atualizar pol\u00edtica" },
      { "RestResponseErrorMsg_Enable_Policy_context", "Ativar pol\u00edtica" },
      { "RestResponseErrorMsg_Get_Metric_Data_context", "Obter dados de m\u00e9trica" },
      { "RestResponseErrorMsg_Get_Policy_context", "Obter pol\u00edtica" },
      { "RestResponseErrorMsg_Get_Scaling_History_context", "Obter hist\u00f3rico de ajuste de escala" },
      { "RestResponseErrorMsg_app_info_not_found_error", "CWSCV6008E: Ocorreu o erro a seguir ao recuperar as informa\u00e7\u00f5es para o aplicativo {0}: {1}." },
      { "RestResponseErrorMsg_app_not_found_error", "CWSCV6007E: O aplicativo n\u00e3o foi localizado: {0}." },
      { "RestResponseErrorMsg_attach_policy_in_Create_Policy_context", "anexando pol\u00edtica em Criar/Atualizar API de pol\u00edtica" },
      { "RestResponseErrorMsg_cloud_error", "CWSCV6006E: Falha ao chamar APIs CloudFoundry: {0}." },
      { "RestResponseErrorMsg_create_policy_in_Create_Policy_context", "criando pol\u00edtica em Criar/Atualizar API de pol\u00edtica" },
      { "RestResponseErrorMsg_delete_policy_in_Delete_Policy_context", "excluindo pol\u00edtica em Excluir API de pol\u00edtica" },
      { "RestResponseErrorMsg_detach_policy_in_Delete_Policy_context", "removendo pol\u00edtica em Criar/Atualizar API de pol\u00edtica" },
      { "RestResponseErrorMsg_enable_policy_in_Enable_Policy_context", "ativando pol\u00edtica em Ativar API de pol\u00edtica" },
      { "RestResponseErrorMsg_get_history_in_Get_History_context", "obtendo hist\u00f3rico em Obter API de hist\u00f3rico" },
      { "RestResponseErrorMsg_get_metric_in_Get_Metric_context", "obtendo m\u00e9trica em Obter API de m\u00e9trica" },
      { "RestResponseErrorMsg_get_policy_in_Get_Policy_context", "obtendo pol\u00edtica em Obter API de pol\u00edtica" },
      { "RestResponseErrorMsg_input_json_format_error", "CWSCV6003E: Erro de formato de sequ\u00eancias JSON de entrada: {0} no JSON de entrada para a API: {1}." },
      { "RestResponseErrorMsg_input_json_format_location_error", "CWSCV6012E: Erro de formata\u00e7\u00e3o na linha {1} coluna {2} nas sequ\u00eancias JSON de entrada para API: {0}." },
      { "RestResponseErrorMsg_input_json_parse_error", "CWSCV6001E: O servidor API n\u00e3o pode analisar as sequ\u00eancias JSON de entrada para a API: {0}." },
      { "RestResponseErrorMsg_internal_authentication_failed_error", "CWSCV6011E: Falha na autentica\u00e7\u00e3o interna durante o {0}." },
      { "RestResponseErrorMsg_internal_server_error", "CWSCV6005E: O erro interno do servidor ocorreu durante {0}." },
      { "RestResponseErrorMsg_output_json_format_error", "CWSCV6004E: Erro de formato de sequ\u00eancias JSON de sa\u00edda: {0} no JSON de sa\u00edda para a API: {1}." },
      { "RestResponseErrorMsg_output_json_parse_error", "CWSCV6002E: O servidor API n\u00e3o pode analisar as sequ\u00eancias JSON de sa\u00edda para a API: {0}." },
      { "RestResponseErrorMsg_parse_input_json_context", "analisar JSON de entrada" },
      { "RestResponseErrorMsg_policy_not_exist_error", "CWSCV6010E: A pol\u00edtica para App {0} n\u00e3o foi localizada." },
      { "RestResponseErrorMsg_retrieve_application_service_information_context", "recuperar informa\u00e7\u00f5es do servi\u00e7o de aplicativo" },
      { "RestResponseErrorMsg_retrieve_org_sapce_information_context", "recuperar informa\u00e7\u00f5es de org/espa\u00e7o" },
      { "RestResponseErrorMsg_service_not_found_error", "CWSCV6009E: Servi\u00e7o: {0} para App {1} n\u00e3o foi localizado." },
      { "RestResponseErrorMsg_update_policy_in_Create_Policy_context", "atualizando pol\u00edtica em Criar/Atualizar a API de pol\u00edtica" }
   };
}
