autoscaler:
    scalingengine:
        url: {{ .ScalingEngineUri }}
client:
    httpClientTimeout: {{ .HttpClientTimeout }}
    ssl:
        protocol: TLSv1.3
endpoints:
    enabled: false
org:
    quartz:
        scheduler:
            instanceId: 0
            instanceName: app-autoscaler
scalingengine:
    notification:
        reschedule:
            maxcount: 3
scalingenginejob:
    reschedule:
        interval:
            millisecond: 10000
        maxcount: 3
scheduler:
    healthserver:
        port: 0
server:
    forward-headers-strategy: framework
    port: {{ .Port }}
    http:
        port: {{ .HttpPort }}
    ssl:
        ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        enabled-protocols: TLSv1.3
        bundle: "server"
        client-auth: NEED
cfserver:
  validOrgGuid: some-org-guid
  validSpaceGuid: some-space-guid
spring:
    aop:
        auto: false
    application:
        name: scheduler
    data:
        jpa:
            repositories:
                enabled: false
    datasource:
        driverClassName: {{ .DriverClassName }}
        password: {{ .DBPassword }}
        url: {{ .JDBCURI }}
        username: {{ .DBUser }}
    main:
        allow-bean-definition-overriding: true
    mvc:
        servlet:
            load-on-startup: 1
    policy-db-datasource:
        driverClassName: {{ .DriverClassName }}
        password: {{ .DBPassword }}
        url: {{ .JDBCURI }}
        username: {{ .DBUser }}
    quartz:
        properties:
            org:
                quartz:
                    jobStore:
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
                        isClustered: true
                        misfireThreshold: 120000
                    scheduler:
                        instanceId: scheduler-12345
                        instanceName: app-autoscaler
                    threadPool:
                        threadCount: 10
    ssl:
        bundle:
            pem:
              server:
                keystore:
                  certificate: file:{{ .TestCertDir }}/scheduler.crt
                  private-key: file:{{ .TestCertDir }}/scheduler.key
                truststore:
                  certificate: file:{{ .TestCertDir }}/autoscaler-ca.crt
              scalingengine:
                  keystore:
                    certificate: file:{{ .TestCertDir }}/scalingengine.crt
                    private-key: file:{{ .TestCertDir }}/scalingengine.key
                  truststore:
                    certificate: file:{{ .TestCertDir }}/autoscaler-ca.crt
