---
name: Check Java Code
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash


concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository content
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          submodules: true
      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: 'true'
      - name: Make devbox shellenv available
        run: |
          eval "$(devbox shellenv)"
          printenv >> "$GITHUB_ENV"
      - name: Check Code Formatting
        run: |
          make --directory=scheduler check-format check-style
      - name: Check for deprecated API usage
        run: |
          make --directory=scheduler check-deprecations
