name: Linters

on:
  pull_request:
  workflow_dispatch:

jobs:
  linters:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Trust my checkout
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: 'true'
      - name: Make devbox shellenv available
        uses: ./.github/actions/devbox-shellenv

      - name: Run Go linter
        run: |
          make lint-go
      - name: shellcheck
        uses: reviewdog/action-shellcheck@a94d585085f1f5215ae65f4de34e7bbd0523d550 # v1
        with:
          reporter: github-pr-check
          fail_level: error
      - name: actionlint
        uses: reviewdog/action-actionlint@320fcdd9c860767cf17fab3b20e22e739d5d02b8 # v1
        with:
          reporter: github-pr-review
      - name: markdownlint
        uses: reviewdog/action-markdownlint@d7862f0a8dbbee78e016f527260747a4f2bb2a64 # v0
        with:
          reporter: github-pr-review
