---
name: Promote Draft Release to Final

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  promote-release:
    runs-on: ubuntu-latest
    name: Promote draft release to final
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0  # Fetch all history for version determination
          ssh-key: ${{ secrets.AUTOSCALER_DEPLOY_KEY_PRIVATE }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: true

      - name: Promote draft release to final
        env:
          GH_TOKEN: ${{ github.token }}
          AUTOSCALER_CI_BOT_EMAIL: ${{ vars.AUTOSCALER_CI_BOT_EMAIL }}
          AUTOSCALER_CI_BOT_NAME: ${{ vars.AUTOSCALER_CI_BOT_NAME }}
          AUTOSCALER_CI_BOT_SIGNING_KEY_PUBLIC: ${{ secrets.AUTOSCALER_CI_BOT_SIGNING_KEY_PUBLIC }}
          AUTOSCALER_CI_BOT_SIGNING_KEY_PRIVATE: ${{ secrets.AUTOSCALER_CI_BOT_SIGNING_KEY_PRIVATE }}
        run: |
          devbox run make --debug release-promote

      - name: Push version bump commit and updated tag
        run: |
          git push --force-with-lease
          git push -f origin --tags
