name: Check if go.mod is tidy
on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check-tidy-go-mod:
    name: ensure that go mod tidy has run
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: true

      - name: Trust my checkout
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: run go mod tidy on all .mod's
        shell: bash
        run: |
          #! /usr/bin/env bash
          set -eu -o pipefail

          devbox run make generate-openapi-generated-clients-and-servers generate-fakes
          devbox run make go-mod-tidy

      - name: Check if there is any change
        id: get_changes
        shell: bash
        run: |
          #! /usr/bin/env bash
          set -eu -o pipefail

          echo "changed=$(git status --porcelain | wc -l)" >> "${GITHUB_OUTPUT}"
          git status
          git diff --diff-algorithm='minimal' --word-diff

      - name: Process changes
        if: steps.get_changes.outputs.changed != 0
        run: |
          echo "::error::go.mod is not tidy, run make go-mod-tidy to tidy"
          exit 1
